version: '2'
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
    env_file:
      - .env
    links:
      - postgres
      - redis
    volumes:
      - .:/var/www
      - ./docker/php/logs:/var/log
    command: sh /docker-command.sh
  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    env_file:
      - .env
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - ./docker/postgres/data:/data/postgres
    #command: sh /docker-command.sh
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /data/postgres
  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - ./docker/redis/data:/data
    #command: sh /docker-command.sh
